export declare type LogWriter = (text: string) => boolean;
export declare type LogLevel = "trace" | "debug" | "info" | "warn" | "error" | "nothing";
export declare const BACKGROUND: {
    BLACK: string;
    RED: string;
    GREEN: string;
    YELLOW: string;
    BLUE: string;
    MAGENTA: string;
    CYAN: string;
    WHITE: string;
    EXTENDED: string;
    DEFAULT: string;
    BRIGHT_BLACK: string;
    BRIGHT_RED: string;
    BRIGHT_GREEN: string;
    BRIGHT_YELLOW: string;
    BRIGHT_BLUE: string;
    BRIGHT_MAGENTA: string;
    BRIGHT_CYAN: string;
    BRIGHT_WHITE: string;
};
export declare const COLOR: {
    BLACK: string;
    RED: string;
    GREEN: string;
    YELLOW: string;
    BLUE: string;
    MAGENTA: string;
    CYAN: string;
    WHITE: string;
    EXTENDED: string;
    DEFAULT: string;
    BRIGHT_BLACK: string;
    BRIGHT_RED: string;
    BRIGHT_GREEN: string;
    BRIGHT_YELLOW: string;
    BRIGHT_BLUE: string;
    BRIGHT_MAGENTA: string;
    BRIGHT_CYAN: string;
    BRIGHT_WHITE: string;
};
export declare function colorify(o: any): string;
export declare const TRACE = "trace";
export declare const DEBUG = "debug";
export declare const INFO = "info";
export declare const WARN = "warn";
export declare const ERROR = "error";
export declare const NOTHING = "nothing";
export declare function log(strings: TemplateStringsArray | any, ...keys: any[]): void;
export declare function trace(strings: TemplateStringsArray | any, ...keys: any[]): void;
export declare function debug(strings: TemplateStringsArray | any, ...keys: any[]): void;
export declare function info(strings: TemplateStringsArray | any, ...keys: any[]): void;
export declare function warn(strings: TemplateStringsArray | any, ...keys: any[]): void;
export declare function error(strings: TemplateStringsArray | any, ...keys: any[]): void;
export declare function includes(level: string): boolean;
declare const _default: typeof log & {
    TRACE: string;
    DEBUG: string;
    INFO: string;
    WARN: string;
    ERROR: string;
    NOTHING: string;
    log: typeof log;
    trace: typeof trace;
    debug: typeof debug;
    info: typeof info;
    warn: typeof warn;
    error: typeof error;
    includes: typeof includes;
    writer: LogWriter;
    level: LogLevel;
};
export default _default;
