export declare type LogWriter = (text: string) => boolean;
export declare type LogLevel = "trace" | "debug" | "info" | "warn" | "error" | "nothing";
export declare type TaggedTemplateLogger = (strings: string | TemplateStringsArray, ...keys: any[]) => void;
export declare type LoggerObject = {
    TRACE: "trace";
    DEBUG: "debug";
    INFO: "info";
    WARN: "warn";
    ERROR: "error";
    NOTHING: "nothing";
    trace: TaggedTemplateLogger;
    debug: TaggedTemplateLogger;
    info: TaggedTemplateLogger;
    warn: TaggedTemplateLogger;
    error: TaggedTemplateLogger;
    setLevel(level: LogLevel): void;
    includes(level: string): boolean;
    get writer(): LogWriter;
    set writer(writer: LogWriter);
    get level(): LogLevel;
    set level(level: LogLevel | number);
};
export declare const BACKGROUND: {
    BLACK: string;
    RED: string;
    GREEN: string;
    YELLOW: string;
    BLUE: string;
    MAGENTA: string;
    CYAN: string;
    WHITE: string;
    EXTENDED: string;
    DEFAULT: string;
    BRIGHT_BLACK: string;
    BRIGHT_RED: string;
    BRIGHT_GREEN: string;
    BRIGHT_YELLOW: string;
    BRIGHT_BLUE: string;
    BRIGHT_MAGENTA: string;
    BRIGHT_CYAN: string;
    BRIGHT_WHITE: string;
};
export declare const COLOR: {
    BLACK: string;
    RED: string;
    GREEN: string;
    YELLOW: string;
    BLUE: string;
    MAGENTA: string;
    CYAN: string;
    WHITE: string;
    EXTENDED: string;
    DEFAULT: string;
    BRIGHT_BLACK: string;
    BRIGHT_RED: string;
    BRIGHT_GREEN: string;
    BRIGHT_YELLOW: string;
    BRIGHT_BLUE: string;
    BRIGHT_MAGENTA: string;
    BRIGHT_CYAN: string;
    BRIGHT_WHITE: string;
};
declare const _default: TaggedTemplateLogger & LoggerObject;
export default _default;
