"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = [
    `\x1B[90mYou’re going to go through tough times – that’s life. But I say, ‘Nothing happens to you, it happens for you.’ See the positive in negative events \x1B[39m– Joel Osteen`,
    `\x1B[90mTough times never last, but tough people do \x1B[39m– Robert H. Schuller`,
    `\x1B[90mWe’ve gotten through a lot of tough times, and we’re going to keep working to make them better. I wish the record was better \x1B[39m– Mike Quade`,
    `\x1B[90mWe must accept finite disappointment, but we must never lose infinite hope \x1B[39m– Martin Luther King`,
    `\x1B[90mWe must embrace pain and burn it as fuel for our journey \x1B[39m– Kenji Miyazawa`,
    `\x1B[90mA problem is a chance for you to do your best \x1B[39m– Duke Ellington`,
    `\x1B[90mProblems are not stop signs, they are guidelines \x1B[39m– Robert Schuller`,
    `\x1B[90mThe greatest glory in living lies not in never failing, but in rising every time we fail \x1B[39m– Nelson Mandela`,
    `\x1B[90mNo matter how bad things are, you can always make things worse \x1B[39m– Randy Pausch`,
    `\x1B[90mLife is at its best when everything has fallen out of place, and you decide that you’re going to fight to get them right, not when everything is going your way and everyone is praising you \x1B[39m– Thisuri Wanniarachchi`,
    `\x1B[90mIt’s funny how, when things seem the darkest, moments of beauty present themselves in the most unexpected places \x1B[39m– Karen Marie Moning`,
    `\x1B[90mThe ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge and controversy \x1B[39m– Martin Luther King, Jr.`,
    `\x1B[90mWhen you come to the end of your rope, tie a knot and hang on \x1B[39m– Franklin D. Roosevelt`,
    `\x1B[90mTo be tested is good. The challenged life may be the best therapist \x1B[39m– Gail Sheehy`,
    `\x1B[90mLet perseverance be your engine and hope your fuel \x1B[39m– H. Jackson Brown, Jr.`,
    `\x1B[90mSeeds of faith are always within us; sometimes it takes a crisis to nourish and encourage their growth \x1B[39m– Susan Taylor`,
    `\x1B[90mIf you are going through hell, keep going \x1B[39m– Winston Churchill`,
    `\x1B[90mHard times don’t create heroes. It is during the hard times when the ‘hero’ within us is revealed \x1B[39m– Bob Riley`,
    `\x1B[90mI am not afraid of storms, for I am learning how to sail my ship \x1B[39m– Louisa May Alcott`,
    `\x1B[90mI have no regrets in my life. I think that everything happens to you for a reason. The hard times that you go through build character, making you a much stronger person \x1B[39m– Rita Mero`,
    `\x1B[90mHard times always lead to something great \x1B[39m– Betsey Johnson`,
    `\x1B[90mSuccess is not final, failure is not fatal: it is the courage to continue that counts \x1B[39m– Winston Churchill`,
    `\x1B[90mLife’s challenges are not supposed to paralyze you, they’re supposed to help you discover who you are \x1B[39m– Bernice Johnson Reagon`,
    `\x1B[90mNew beginnings are often disguised as painful endings \x1B[39m– Lao Tzu`,
    `\x1B[90mIt is not because things are difficult that we do not dare; it is because we do not dare that they are difficult \x1B[39m– Seneca`,
    `\x1B[90mWhen the going gets tough, the tough get going \x1B[39m– Joseph Kennedy`,
    `\x1B[90mNever give up on something that you can’t go a day without thinking about \x1B[39m– Sir Winston Churchill`,
    `\x1B[90mMost of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no hope at all \x1B[39m– Dale Carnegie`,
    `\x1B[90mLife is like riding a bicycle. To keep your balance, you must keep moving \x1B[39m– Albert Einstein`,
    `\x1B[90mIt’s not that I’m so smart, it’s just that I stay with problems longer \x1B[39m– Albert Einstein`,
    `\x1B[90mOur greatest glory is not in never falling, but in rising every time we fall \x1B[39m– Confucius`,
    `\x1B[90mWe must meet the challenge rather than wish it were not before us \x1B[39m– William J. Brennan, Jr.`,
    `\x1B[90mMany of life’s failures are people who did not realize how close they were to success when they gave up \x1B[39m– Thomas Edison`,
    `\x1B[90mAccept responsibility for your life. Know that it is you who will get you where you want to go, no one else \x1B[39m– Les Brown`,
    `\x1B[90mYou need to spend time crawling alone through shadows to truly appreciate what it is to stand in the sun \x1B[39m– Shaun Hick`,
    `\x1B[90mIf God sends us on strong paths, we are provided strong shoes \x1B[39m– Corrie ten Boom`,
    `\x1B[90mI ask not for a lighter burden, but for broader shoulders \x1B[39m– Jewish Proverb`,
    `\x1B[90mI have not failed. I’ve just found 10,000 ways that won’t work \x1B[39m– Thomas Alva Edison`,
    `\x1B[90mThankfully, persistence is a great substitute for talent \x1B[39m– Steve Martin`,
    `\x1B[90mI think that little by little I’ll be able to solve my problems and survive \x1B[39m– Frida Kahlo`,
    `\x1B[90mIf you feel like giving up, give up on that feeling and give into the realization there are endless possibilities waiting to be discovered before you \x1B[39m– Tom Althouse`,
    `\x1B[90mEncourage yourself, believe in yourself, and love yourself. Never doubt who you are \x1B[39m– Stephanie Lahart`,
    `\x1B[90mPain is your friend; it is your alie. Pain reminds you to finish the job and get the hell home. Pain tells you when you have been seriously wounded. And you know what the best thing about pain is? It tells you you’re not dead yet! \x1B[39m– G.I Jane`,
    `\x1B[90mA problem is a chance for you to do your best \x1B[39m– Duke Ellington`,
    `\x1B[90mWhen everything seems to be going against you, remember that the airplane takes off against the wind, not with it \x1B[39m– Henry Ford`,
    `\x1B[90mIn times of great stress or adversity, it’s always best to keep busy, to plow your anger and your energy into something positive \x1B[39m– Lee Iacocca`,
    `\x1B[90mIf someone is strong enough to bring you down, show them you are strong enough to get back up \x1B[39m– A. Josland`,
    `\x1B[90mDo not pray for an easy life, pray for the strength to endure a difficult one \x1B[39m– Bruce Lee`,
    `\x1B[90mYou’ve got to Stay Strong to be strong in tough times \x1B[39m– Tilman J. Fertitta`,
    `\x1B[90mStorms make trees take deeper roots \x1B[39m– Dolly Parton`,
    `\x1B[90mAll of life is a test and we all have our challenges to meet \x1B[39m– Marjory Sheba`,
    `\x1B[90mIt is a blessing to experience hardship. Not because we suffer, but because we learn to endure \x1B[39m– Saim .A. Cheeda`,
    `\x1B[90mSee your hard times through the spectacles of your experiences. They, too, shall pass away \x1B[39m– Ogwo David Emenike`,
    `\x1B[90mIt’s true that no one ever said life would be easy, but it is also true that no one ever said you had to go through it alone \x1B[39m– Jellis Vaes`,
    `\x1B[90mIt takes a lot of courage to push through hard times. Never give up. Good things are coming your way \x1B[39m– Robert Tew`,
    `\x1B[90mIn my experience, people who don’t stick around during the hard times weren’t worth having around anyway \x1B[39m– Kimberly Belle`,
    `\x1B[90mHard times are like thunder. They make a lot of noise but do little harm. Don’t fear hard times \x1B[39m– Debasish Mridha`,
    `\x1B[90mSome roses grow through concrete. Remember that \x1B[39m– Brandi L. Bates`,
    `\x1B[90mWhen hardships keep coming back, do not take it personal. It’s just life \x1B[39m– Naide P Obiang`,
    `\x1B[90mI’ll tell you something about tough times. They just about kill you, but if you decide to keep working at them, you’ll find your way through \x1B[39m– Joan Bauer`,
    `\x1B[90mLife keeps throwing me stones. And I keep finding the diamonds... \x1B[39m– Ana Claudia Antunes`,
    `\x1B[90mAttitude-flexibility is the mentality that helps us to smoothly persevere through turbulent times \x1B[39m– Dr. Jacinta Mpalyenkana`,
    `\x1B[90mNever give up. Things may be hard, but if you quit trying they’ll never get better. Stop worrying and start trusting God. It will be worth it \x1B[39m– Germany Kent`,
    `\x1B[90mDifficult times will come. It’s a fact of life, isn’t it? There are good times and bad times in everybody’s life \x1B[39m– Raj Kosaraju`,
    `\x1B[90mHard times lifts the seeking souls to higher spiritual realms \x1B[39m– Lailah Gifty Akita`,
    `\x1B[90mI like to use the hard times of the past to motivate me today \x1B[39m– Dwayne Johnson`,
    `\x1B[90mHard times may have held you down, but they will not last forever. When all is said and done, you will be increased \x1B[39m– Joel Osteen`,
    `\x1B[90mHard times, when held with open hands and a tender heart, can prepare us for the future \x1B[39m– Cindee Snider Re`,
    `\x1B[90mSometimes adversity is what you need to face in order to become successful \x1B[39m– Zig Ziglar`,
    `\x1B[90mHard times may have put you down sometimes but they will not last forever. When all is said and done, you will be wise and strong \x1B[39m– Anurag Prakash Ray`,
    `\x1B[90mIf you are being positive and strong in difficult times half of your problems will be solved automatically \x1B[39m– Anurag Prakash`,
    `\x1B[90mEnthusiasm is common. Endurance is rare \x1B[39m– Angela Duckworth`,
    `\x1B[90mHard times sustain and strengthen others, inspiring them to strive toward personal growth \x1B[39m– Senora Roy`,
    `\x1B[90mHard times arouse an instinctive desire for authenticity \x1B[39m– Coco Chanel`,
    `\x1B[90mGoing through challenging things can teach you a lot, and they also make you appreciate the times that aren’t so challenging \x1B[39m– Carrie Fisher`,
    `\x1B[90mYou may not realize it when it happens, but a kick in the teeth may be the best thing in the world for you \x1B[39m– Walt Disney`,
    `\x1B[90mAdversity is like a strong wind. It tears away from us all but the things that cannot be torn, so that we see ourselves as we really are \x1B[39m– Arthur Golden`,
    `\x1B[90mIf you’re feeling low, don’t despair. The sun has a sinking spell every night, but it comes back up every morning. The way I see it, if you want the rainbow, you gotta put up with the rain \x1B[39m– Dolly Parton`,
    `\x1B[90mOne ceases to recognize the significance of mountain peaks if they are not viewed occasionally from the deepest valleys \x1B[39m– Dr. Al Lorin`,
    `\x1B[90mIf you can find a path with no obstacles, it probably doesn’t lead anywhere \x1B[39m– Frank A. Clark`,
    `\x1B[90mI have sometimes been wildly, despairingly, acutely miserable, but through it all I still know quite certainly that just to be alive is a grand thing \x1B[39m– Agatha Christie`,
    `\x1B[90mIn the midst of winter, I finally learned that there was in me an invincible summer \x1B[39m– Albert Camus`,
    `\x1B[90mIn the middle of difficulty lies opportunity \x1B[39m– Albert Einstein`,
    `\x1B[90mI know God will not give me anything I can’t handle. I just wish that He didn’t trust me so much \x1B[39m– Mother Teresa`,
    `\x1B[90mWhen it is dark enough, you can see the stars \x1B[39m– Ralph Waldo Emerson`,
    `\x1B[90mThe difference between stumbling blocks and stepping stones is how you use them \x1B[39m– Unknown`,
    `\x1B[90mThe signature of the truly great is not the absence of difficulty but the ability to recover from setbacks \x1B[39m– Jim Collins`,
    `\x1B[90mWhat lies behind you and what lies in front of you, pales in comparison to what lies inside of you \x1B[39m– Ralph Waldo Emerson`,
    `\x1B[90mDon’t let what you cannot do interfere with what you can do \x1B[39m– John R. Wooden`,
    `\x1B[90mNever let your head hang down. Never give up and sit down and grieve. Find another way. And don’t pray when it rains if you don’t pray when the sun shines \x1B[39m– Leroy Satchel Paige`,
    `\x1B[90mYou may have to fight a battle more than once to win it \x1B[39m– Margaret Thatcher`,
    `\x1B[90mThe bravest sight in the world is to see a great man struggling against adversity \x1B[39m– Seneca`,
    `\x1B[90mIt is better to die on your feet than to live on your knees \x1B[39m– Emiliano Zapata`,
    `\x1B[90mObstacles don’t have to stop you. If you run into a wall, don’t turn around and give up. Figure out how to climb it, go through it, or work around it \x1B[39m– Michael Jordan`,
    `\x1B[90mYou’ll never regret what you do in life. You’ll only regret what you don’t do \x1B[39m– Dr. Wayne Dyer`,
    `\x1B[90mYour friends will believe in your potential, your enemies will make you live up to it \x1B[39m– Tim Fargo`,
    `\x1B[90mFaith is why I’m here today and faith is why I made it through \x1B[39m– Jonathan Anthony Burkett`,
    `\x1B[90mYou start with a darkness to move through but sometimes the darkness moves through you \x1B[39m– Dean Young`,
    `\x1B[90mSome people make a bad bed, they just have to lie in it \x1B[39m– Virginia Euwer Wolff`,
    `\x1B[90mAccept hardship as a necessary discipline \x1B[39m– Lailah Gifty Akita`,
    `\x1B[90mHard times and fake friends are like oil and water: they don’t mix \x1B[39m– Nkwachukwu Ogbuagu`,
    `\x1B[90mThe good life is not built on a foundation of ease…it’s the hard times that give us a rock solid foundation \x1B[39m– Richie Norton`,
    `\x1B[90mAs the worst comes to us when we are unprepared, so shall we Strive when the best in unexpected \x1B[39m– Goitsemang Mvula`,
    `\x1B[90mWithout hope, how can we survive hard times? \x1B[39m– Lailah Gifty Akita`,
    `\x1B[90mIn the hard times everything will be revealed, stay watching \x1B[39m– Gun Gun Febrianza`
];
//# sourceMappingURL=quotes.js.map